# Generated by Django 4.2.5 on 2023-09-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(through='elearning.UserLessonHistory', to='elearning.lesson'),
        ),
    ]
