# Generated by Django 4.2.5 on 2023-09-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='length_in_seconds',
            field=models.IntegerField(),
        ),
    ]
