# Generated by Django 4.2.3 on 2023-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearningbe', '0003_remove_userproductlessonhistory_been_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(to='elearningbe.lesson'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
